#! /bin/sh
### BEGIN INIT INFO
# Provides:          fingerprint
# Required-Start:    $ALL
# Required-Stop:
# Should-Start:
# Default-Start:     3
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO


do_start () {
    cd /home/pi/vetty/server
    (VETTY_USERNAME="username" VETTY_PASSWORD="password" /usr/bin/node index.js &)
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: splash [start|stop]" >&2
    exit 3
    ;;
esac
