#! /bin/sh
### BEGIN INIT INFO
# Provides:          splash
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO


do_start () {
    #/usr/bin/fbi -T 1 --noverbose --noedit -a /home/pi/yo.png
    #sleep 5
    #echo "RUNNING MODIFIER..."
    #echo "--------------------"
    cd /home/pi/vetty/display
    #../modifier > ../LOG
    #../modifier
    #echo "$?" >> ../LOG
    #../modifier
    #if [ "$?" -eq 0 ]; then
    #    (/usr/bin/python screentest.py &)
   #echo "-------YAY-------"
    #else
	#/usr/bin/fbi -T 1 --noverbose --noedit -a /home/pi/yo.png
    #echo "-------NAY-------"
    #fi
    (/usr/bin/python image.py &)
    touch ../temp
    cd -
    #sleep 5
    #echo "-------------------"
    #echo "-----DONE----------"
    #sleep 5
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: splash [start|stop]" >&2
    exit 3
    ;;
esac

:
